version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    environment:
      # Opting not to use a required variable here
      # since this will force the NODE_ENV variable
      # requirement during build when this variable
      # currently is only relevant to deployment
      - NODE_ENV
    init: true
    ports:
      - '4000:4000'
