version: '3.8'
services:
  local-mongodb:
    image: mongo:4.4.0-rc13
    container_name: local-mongodb
    environment:
      - MONGO_INITDB_DATABASE=dev-aptitude-db
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-init/dev.db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    # Turning off volumes for the purposes of testing
    # - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
